[tool.black]
target-version = ['py310']
extend-exclude = '''
(
/(
  | venv
)/
)
'''
force-exclude = '''
(
)
'''

[tool.isort]
profile = "black"
extend_skip_glob = ["submodule_name/*"]

[tool.mypy]
python_version = '3.10'
no_silence_site_packages = false
ignore_missing_imports = true
exclude = ['tests/']
